# Generated by Django 2.2 on 2019-04-16 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
