# Generated by Django 2.2 on 2019-04-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0004_auto_20190408_0013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
