# Generated by Django 2.2 on 2019-04-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0007_auto_20190410_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
